### ISSUE TITLE
decoupling model configs from `classify.py`

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-swt-detection#27]
### New Feature Summary

#25 made first implementation of a MMIF wrapper of the model we trained. One of the implementational choice (given time constraint at the time) was hard-coding model configuration into [`classify.py`](https://github.com/clamsproject/app-swt-detection/blob/5d585f3aadedc6e0be69d56a1d44052736797d5c/modeling/classify.py). I request a new feature that basically decouple the model configuration to another generic file (could be `.py`, `.json.` or `.yaml`) thats' imported into `classify.py` and in turn into `app.py` if necessary. 

Moreover, if we can generate such a file from a result report file (such as [this](https://github.com/clamsproject/app-swt-detection/blob/5d585f3aadedc6e0be69d56a1d44052736797d5c/modeling/results/20231025-062850.kfold_results.txt), note that the file contents is somewhat outdated now, and the latest `train.py` requires (and records) more configuration k-v)

**Comment by marcverhagen** [comment]
I think we can close this once the last updates to saving out and loading configuration files are done.
