### ISSUE TITLE
massive refactoring required

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-swt-detection#31]
### Because

As there are many instances of "copies" of python scripts/functions/methods in the project root directory, the codebase is really hard to read and review. For example, I spent 30 mins to figure out why my edits were now properly staged until I realized that there are to `classify.py` files when I first started reviewing the app submission. De-cluttering these stopgap practice will highly improve readability and maintenance of the codebase. 

### Done when

Only one copy of all classes, modules, methods, and functions related to training and classification are left and properly packaged in a python package.

**Comment by keighrim** [comment]
done via #32

**Comment by keighrim** [comment]
Reopening this as we change to course and decided to release `v1.0` with the duplicate code.

**Comment by marcverhagen** [comment]
Duplicate code is gone I think. One remaining thing that I can think of is to split classification of images from generation of timeframes (now they are not closely entangled, but still in the same file).

**Comment by marcverhagen** [comment]
Refactoring will continue, but the massive changes that were needed are all done I think.
