### ISSUE TITLE
implement smoothing when image label >> timeframe conversion

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-swt-detection#33]
### New Feature Summary

In `v1.0`, converting image classification results into `TImeFrame` annotations only performs "stitching" but no smoothing was implemented. In the previous-gen SWT-like apps, we had parameterized smoothing implementations, so I'd like this NG app to also have similar interface. 

### Related

Parameterized smoothing components in previous gen SWT apps. 
* https://apps.clams.ai/fewshotclassifier/v1.0/#configurable-parameters
* https://apps.clams.ai/slatedetection/v2.1/#configurable-parameters 
* https://apps.clams.ai/barsdetection/v1.1/#configurable-parameters
* https://apps.clams.ai/chyron-detection/v1.0/#configurable-parameters

**Comment by marcverhagen** [comment]
The terms stitching and smoothing are somewhat confusing to me.

Parameters used in the previous apps are similar to the ones here in the 14-clamsapp branch (at least minFrameCount and threshold are used, although the latter is called minFrameScore). We should agree on naming, and I like both minFrameScore for its similarity to minFrameCount and threshold for its simplicity.

Further smoothing implementation I think can wait until it is clear that we get something substantial out of it.

**Comment by keighrim** [comment]
v2.0 implemented some of these features. @marcverhagen could you write about your implementation here (or in the code) for documentation and then decide if this issue is resolved?

**Comment by marcverhagen** [comment]
@keighrim High level description of the algorithm is now in the develop branch. 
https://github.com/clamsproject/app-swt-detection/blob/develop/modeling/docs/stitching.md

**Comment by marcverhagen** [comment]
@keighrim This issue is resolved I think, but we should perhaps start a new issue in clams-python on creating a stitcher utility that can be used by any app.
