### ISSUE TITLE
the get_configuration() method throws an error

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#42]
### Because

Maybe this should be an issue on clams-python, but the app crashes with the following error:

```
<class 'TypeError'>: ClamsApp.get_configuration() takes 1 positional argument but 2 were given

  File "/Applications/ADDED/venv/clams/app-swt/lib/python3.11/site-packages/clams/restify/__init__.py", line 146, in post
    return self.json_to_response(self.cla.annotate(raw_data, **self.annotate_param_caster.cast(raw_params)))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	
  File "/Applications/ADDED/venv/clams/app-swt/lib/python3.11/site-packages/clams/app/__init__.py", line 116, in annotate
    annotated = self._annotate(mmif, **runtime_params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	
  File "/Users/marc/Desktop/projects/clams/code/clamsproject/apps/app-swt-detection/app.py", line 46, in _annotate
    parameters = self.get_configuration(parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This was with code at the top of the develop branch. For now I have restored and adapted the previous way of reading configuration settings and updating them with app parameters.

**Comment by keighrim** [comment]
this was my bad, but it should be a trivial fix. https://sdk.clams.ai/autodoc/clams.app.html#clams.app.ClamsApp.get_configuration just make `parameters` into a kwarg.

**Comment by marcverhagen** [comment]
Ah, good. One potential source of trouble there is that we have competing settings in the config file and the parameters, must think that through a little bit.

**Comment by keighrim** [comment]
Largely there are model_configs and stitcher_configs. Once classifier and stitcher are separated into their own modules/classes, there won't be competing conditions (or at least much less of them).

Eventually I'd like to have is just to get rid of classifier.yml at all, and to directly re-use trainer.yml for `Classifier` class and to configure stitcher from the runtime params (passed via CLI or POST call).

**Comment by marcverhagen** [comment]
Maybe three kinds: model, classifier and stitching. 

Model:
- img_enc_name, num_epochs, num_splits, num_layers, dropouts
- block_guids_train, block_guids_valid
- max_input_length
- pos_enc_name, pos_unit, pos_enc_dim

Classifier:
- model_file, model_config_file
- sample_rate

Stitching
- minimum_frame_score, minimum_timeframe_score, minimum_frame_count

There indeed is redundancy between `trainer.yml` and the model config file. But we may need to live with that. If we do not save the the `trainer.yml` information with the model config then we cannot change `trainer.yml` unless we associated the model with a version of `trainer.yml`. Maybe simply copying the trainer config when creating the classifier model would be the easiest.

I do like the idea of choosing for parameters via CLI and POST request wherever we can, probably removing the need for `classifier.yml`.

**Comment by marcverhagen** [comment]
I misread your message a bit I think.

Anyway, what I am suggesting is:

- Directly copy the trainer configuration with the model
- Use POST/CLI parameters where we can, hopefully getting rid of classifier.yml
- Figure out something for the model file and model config file.

**Comment by marcverhagen** [comment]
Fixed in https://github.com/clamsproject/app-swt-detection/commit/0ab78e0c3eda4a601aee021cbf9b05eb77249a5b.

Keeping this open because we the question on how best to do the configuration is still open..

**Comment by marcverhagen** [comment]
Nah, closing it anyway, configuration seems stable.
