### ISSUE TITLE
Classifier app does not know about post binning

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#46]
### Because

The classifier only works well if there is no post binning. It gets its labels from

https://github.com/clamsproject/app-swt-detection/blob/468aa2b6e9bf2e6b69204e71670a6658d0e93fa6/modeling/train.py#L268-L274

And those labels are added to the Prediction instances. If there is post binning than the labels will be out of sink with the Prediction because the scores in the Prediction are for the labels after pre binning, not post binning.

Changes needed are to `Classifier.process_video()` which hands over the wrong labels to the prediction, but mostly to the Stitcher, which now does not know what scores to pick.

Note to self: post binning as implemented in train.py does not involve adding probabilities on post-binned labels, instead it picks the highest score. It should not be hard to experiment with both in the stitcher.

**Comment by marcverhagen** [comment]
Fixed in https://github.com/clamsproject/app-swt-detection/pull/57

**Comment by marcverhagen** [comment]
@keighrim do you know why this was reopened?  CLAMS Bot gone rogue?

**Comment by keighrim** [comment]
It look like the bot assigned this issue to you when you pushed `14-clamsapp-xxx` branch, and as part of assigning action it reopened it. (https://github.com/clamsproject/app-swt-detection/actions/runs/7821239106/job/21337739873)

**Comment by keighrim** [comment]
No that was issue 14, not this one.

**Comment by keighrim** [comment]
Aha, you also pushed `46-postbinning` branch around the same time (and deleted immediately), and bot caught that.

**Comment by marcverhagen** [comment]
Ah, I did accidentally do a `push --all` in stead of a `push --tags` and that included many branches so that could be it. I was the one who went rogue.
