### ISSUE TITLE
Add parameters to specify a partial segment (start time and end time) of the video

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-swt-detection#51]
### New Feature Summary

As a user, when I specify a **start time** and/or an **end time**, the app detects scenes only for that period of the video.  After the end time is reached, no more frames are extracted, and execution completes.

This would allow identification of scenes only within a time period of interest, minimizing the execution time for the app.  This will be especially useful for detecting bars at the beginning of videos.  It is also useful for testing and evaluation.

Suggested names for the new parameters: `startTime` and `endTime`.

**Comment by marcverhagen** [comment]
This should be easy to do. One thing to discuss is what time units to accept. In MMIF we are moving towards a default of using milliseconds, and maybe even disallow other time units. 

But this is not MMIF. And no user in their right mind would probably enjoy using startTime=630000 and endTime=640000 if they want processing limited from 10:30 till 10:40.

**Comment by keighrim** [comment]
Well, I think this is still MMIF , as those parameter values are stored under view metadata in the output MMIF. 

In https://github.com/clamsproject/mmif/issues/192 , we decided to move away from allowing different time units, and stick to an integer type. If the app allows "start" and "end" param values passed as ISO format string, there are few things to consider, off the top of my head; 

1. Allowed granularity 
1. Handling conversion that minimizes any errors 
1. User education
1. Documentation 

First two are not problems if we stick to millisecs. For the rest, then, I think we need to include the time unit name itself as a part of the parameter name to make it transparent without separate , verbose documentation. For example , `startWatchingFromMilliseconds`.

**Comment by owencking** [comment]
From my perspective, values in milliseconds are totally fine for this parameter. 

I'm now in the habit of thinking of all CLAMS/MMIF durations and time markers in terms of milliseconds.

**Comment by marcverhagen** [comment]
Ah, we disagree on whether this is MMIF. I don't think it is. What is MMIF is that milliseconds are the unit for annotation types (assuming we are going that way) and that we have a dictionary of parameters in the metadata. That does not preclude allowing the CLAMS user to specify seconds or an ISO format string and convert 10 seconds to 10000 ms and "1:10" to 70000.

My preferred way is usually to do what is natural for the user, and if that takes some conversion then that is worth it.

Having said that, given Owen's remark it certainly makes sense to go with milliseconds for now.

**Comment by marcverhagen** [comment]
This is done in https://github.com/clamsproject/app-swt-detection/commit/63ef0a5ab15dac87dae379e8710ce62369ad033f, but using `startAt` and `stopAt` instead of the suggested `startTime` and `endTime` in order to stay consistent with other apps.
