### ISSUE TITLE
ConnectionResetError when building the image

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#55]
### Because

While installing the Python requirements with these lines in the container file

```docker
COPY requirements-app.txt .
RUN pip install --no-cache-dir -r /app/requirements-app.txt
```

I get this error on some machines:

```
ConnectionResetError: [Errno 104] Connection reset by peer
```

This has happened in the past as well and I fixed it then by doing individual pip installs, but at some point we reverted to using a requirements file. The issue also happened with older code that installed a model in a rather hacky way, but that one was fixed with the `dl_backbone.py` script.

**Comment by keighrim** [comment]
This could be a server (pypi.org) side issue. Do you keep getting the same 102 error when trying again some time later? 

Or it could be docker network (mos-)configuration or (old) pip exec version.

**Comment by marcverhagen** [comment]
I never tried to build the image repeatedly over an extended time period, so I would have to try that. But it may be the configuration or version issue. I will compare configurations because this issue never happens at work.

**Comment by keighrim** [comment]
closing as non-reproducible and stale.
