### ISSUE TITLE
Use post binning labels in classification

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#72]
The classification now uses raw classification results, then bins them into the four post-bin categories (slate et al). The classification on TimePoint now uses the raw categories, but should use the more user-friendly categories.

This may take away the need to have a scores property on the TimeFrame.

**Comment by marcverhagen** [comment]
Was about to close this, but leave it open while me ponder whether this was a good idea.

**Comment by keighrim** [comment]
was reverted in 145807a / v4.2.
