### ISSUE TITLE
Hard-coded basic categories

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#77]
### Because

The train module defines the categories used:

https://github.com/clamsproject/app-swt-detection/blob/710f527e0d88074815374cf81de320a1f751cfc6/modeling/train.py#L35-L37

This means that adding an additional category requires changing the app. Should looking into moving the definition into a configuration file or some other approach.

**Comment by keighrim** [comment]
The basic labelset has been moved to the package init.py (72266e84b926ebd7070dfea2aac3a735e5e453d0), so no longer specifically a part of `train` scope only. 

And that labelset was never part of "configuration" during training. It was given in the annotation. If we are _adding an additional category_, that means a new different annotation data and different rounds of training. I believe that should a new app. In other words, the fact that these labels are hard-coded in the modeling package doesn't seem to be an issue to me. In fact, I believe they have to be hard-coded, not "configurable".

**Comment by marcverhagen** [comment]
Having this in outside of train.py is much better.

And if we create a new app each time we have a different annotation then this is indeed not a configuration issue but a basic annotation data issue.

At some point we may need to think about the similarity between all kinds of SWT-like apps and if there is value in de-appifying some training-classification code (similar to what is being done with the stitcher).

But in general it is now fine to close this.
