### ISSUE TITLE
Record all parameter values (including defaults) in output MMIF

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-swt-detection#84]
### New Feature Summary

Desired functionality:  
When the SWT app is run, the values of all parameters, including those implicitly assigned default values, are recorded in
`views` > n > `metadata` > `parameters`

In v4.1 (and previous versions), parameters are recorded in the MMIF only if they were set explicitly at runtime.

Since different versions of the same app can have different default values for the parameters, having all the parameter values explicitly recorded in the MMIF makes it easier to investigate how a particular MMIF file was generated.

### Additional context

This seems to me like desirable functionality to have in all CLAMS apps, not only SWT.

**Comment by keighrim** [comment]
This was actually discussed in https://github.com/clamsproject/mmif/issues/208, then reverted via https://github.com/clamsproject/mmif/pull/217. We can always revisit our previous decision, but a couple things to note;  

1. we can't (re-)use `view::metadata::parameters` for this, as we want to keep that field for pure user inputs (for reproducibility and accountability)
2. which leads to an addition of a new field, that will lead to a "breaking" change in MMIF json scheme and will end up with MMIF 1.1.x.

**Comment by keighrim** [comment]
Closing as duplicate to https://github.com/clamsproject/mmif/issues/208 , as that issue is now re-opened for further discussion.
