### ISSUE TITLE
startAt and stopAt parameters not honored

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-swt-detection#85]
### Bug Description

When values for `startAt` and `stopAt` are passed to the SWT app, those values should define the time range of annotated timepoints.  As of now, at least in v4.1, these values seem to be ignored.

If you run the app with values for these parameters, the app will nevertheless process the entire video and produce annotations across the entire duration.

### Reproduction steps

Specify `startAt` and/or `stopAt` parameters via a query string to SWT running as a web service, as with this query string: `startAt=1237500&stopAt=1767000`.  SWT still begins annotating at 0ms and continues to 1784500ms.

The asset used during testing: cpb-aacip-37-95w6mnpw

**Comment by marcverhagen** [comment]
Did a post-mortem on this because I knew that this error did not happen when I added the parameters. Turns out that `_export_parameters()`, an essential method for this, was removed after version v4.0. This somehow went unnoticed.
