### ISSUE TITLE
increase default value for `stopAt` parameter

### ISSUE THREAD

**Issue by owencking** [clamsproject/app-swt-detection#95]
### Because

The current default for `stopAt` is 10,000,000 ms.  This is less than 3 hours.  Although it would be unusual, it is possible that an AAPB video could be longer than that.

I'd recommend a default value of 86,400,000 ms, which is 24 hours.

**Comment by keighrim** [comment]
After reading this issue, I was tempted to use the maximum integer value. Then, I found this comment in the code; 

https://github.com/clamsproject/app-swt-detection/blob/710f527e0d88074815374cf81de320a1f751cfc6/metadata.py#L42-L43

@marcverhagen is this about python 2 v. 3 compatibility issue of `sys.maxint`?

**Comment by marcverhagen** [comment]
@keigh Not sure why I thought 10M is better than maxsize (old habit of mine to use maxint, not about compatibility issues). Maybe I did not want a default that would allow processing to continue for years, but why not?

I have changed this to use sys.maxsize and this will be in version 5.0.

**Comment by owencking** [comment]
From the [v5.0 app directory page](https://apps.clams.ai/swt-detection/v5.0/):
> stopAt: optional, defaults to 9223372036854775807

Yeah, I think that should be just about high enough.  LOL

(Also, thank you!)
