### ISSUE TITLE
Add CLI capabilities

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/app-swt-detection#97]
### Because

This was requested by GBH and is in the works in a more general way, but it would be nice to have this asap for this app. Possibly based on the work in the test_cli_interface branch.

**Comment by marcverhagen** [comment]
Added some code in e6662c4 and 43a3fbb05e, but there is still an issue with some parameters.

**Comment by keighrim** [comment]
fixed via https://github.com/clamsproject/clams-python/pull/217 and https://github.com/clamsproject/app-swt-detection/pull/106.
